#!/usr/bin/env python3
import requests
import random
import glob
import os

def stdout(quote):
    if len(quote) >= 65:
        quote = quote[0:62] + "..."
    this = '"%s"' % quote 
    this += ' - Kanye West'
    print(this)

def kanye_save(content, rnd_no):
    with open(f"/usr/local/bin/_kanye/{rnd_no}.txt", "w") as f:
        f.write(content)

def kanye_get():    
    rnd_no = random.random()
    if rnd_no > 0.995:
        response = requests.get("https://api.kanye.rest/")
        kanye = response.json().get("quote")
        kanye_save(kanye, rnd_no)
        return stdout(kanye)
    
    list_o_quotes = glob.glob("/usr/local/bin/_kanye/*")
    latest_file = random.choice(list_o_quotes)
    with open(latest_file, "r") as f:
        quote = f.read()
    return stdout(quote)

kanye_get()

